# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  run-tests:
    executor:
      name: node/default
      tag: '20.9.0'
    steps:
      - checkout
      - node/install-packages
      - run: npm run test

workflows:
  run-test-workflow:
    jobs:
      - run-tests
